<a href="https://colab.research.google.com/github/Patilla4puto/Intro_to_ml-tokio_school/blob/master/02-entorno_de_trabajo/modulo1-unidad2-ejercicio3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a las librerías usadas

En este notebook veremos una breve introducción a las librerías:
- Jupyter
- Numpy
- Matplotlib
- Scikit-learn

El "kernel" o lenguaje usado por el notebook y las librerías es Python 3.

Para este ejercicio, simplemente ejecuta todas las celdas y revisa las diferentes funciones utilizadas. Al final del mismo tendrás unos pocos ejercicios para resolver.

In [ ]:
import numpy as np

n = np.arange(27).reshape((3, 3, 3))

print(n[:,2,2])
print(n)

[ 8 17 26]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


## Jupyter

Jupyter permite incluir en un único documento "celdas" con código interactivo, texto explicativo, resultados y gráficas. Código interactivo puesto que podemos modificar el código y ejecutarlo desde cualquier celda.
Los notebooks de Jupyter son __colaborativos__, __fácilmente compartidos__, __pensados para ser publicados__ y, sobretodo, __reproducibles__.
Por todo eso y más son ideales para ser usados en educación, computación científica y, en especial, en _big data_ y análisis de datos.

Ejecutar código es tan sencillo como incluir una celda de código y pulsar "Run" (o CTRL + Enter):

In [2]:
import jupyter, numpy, matplotlib, sklearn
print(jupyter.__version__)
print(numpy.__version__)
print(matplotlib.__version__)
print(sklearn.__version__)

1.0.0
1.19.5
3.2.2
1.0.1


Tras cada celda se muestra el resultado de su ejecución, que puede ser intercalado con celdas de texto explicativo.
Dicho texto se formatea con [__markdown__](https://markdown.es/).

In [ ]:
a = 1
b = 2
c = 4

In [ ]:
print(a)
print(b)
print(c)

marcos
b
marcosb


In [ ]:
a = 'marcos'
b = 'b'
c = a + b
print(c)

marcosb


Prueba a ejecutar de nuevo el código que imprime el valor de las variables "a", "b" y "c". A ésto nos referimos cuando hablamos de código interactivo.

Inserta una celda tras ésta copiando el código de la última celda de código, modifica los valores de las variables "a" y "b" y ejecútala. Al ser un notebook interactivo, puedes incluir nuevas celdas para modificar la ejecución, por ejemplo para encontrar errores o comprender mejor cómo se ejecuta el código.

## Numpy

Librería para cálculo numérico de referencia en Python.

In [5]:
import numpy as np
print(np.__version__)

1.19.5


In [ ]:
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
b = np.array([[1,2,3],[3,4,5]])
print(b)
print(b.ndim)
print(b.shape)

[[1 2 3]
 [3 4 5]]
2
(2, 3)


In [ ]:
b = b.reshape(3,2)
print(b)
print(b.ndim)
print(b.shape)

[[1 2]
 [3 3]
 [4 5]]
2
(3, 2)


In [ ]:
c = np.array([1,2,3], ndmin = 3, dtype = complex)
print(c)
print(c.ndim)
print(c.shape)
print(c.dtype)

[[[1.+0.j 2.+0.j 3.+0.j]]]
3
(1, 1, 3)
complex128


In [28]:
d = np.arange(24)
print(d)
print(d.ndim)
e = d.reshape(2,4,3)
print(e)
print(e.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
3


In [ ]:
f = np.empty([3,2], dtype = int)
g = np.zeros((2,2))
h = np.ones(5)
print(f)
print(g)
print(h)

[[94642079568384              0]
 [             0              0]
 [             0              0]]
[[0. 0.]
 [0. 0.]]
[1. 1. 1. 1. 1.]


In [ ]:
i = np.asarray(range(4))
print(i)

[0 1 2 3]


In [ ]:
j = np.linspace(10,20,5)
k = np.logspace(1,2,num=10)
print(j)
print(k)

[10.  12.5 15.  17.5 20. ]
[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [ ]:
l = np.arange(10)
print(l)
print(l[3])
print(l[2:7])
print(l[2:7:2])
s = slice(2,7,2)
print(l[s])
l[3] = 42
print(l)

[0 1 2 3 4 5 6 7 8 9]
3
[2 3 4 5 6]
[2 4 6]
[2 4 6]
[ 0  1  2 42  4  5  6  7  8  9]


In [ ]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print('Fila 1 en adelante:\n', m[1:])
print('Columna 1 en adelante:\n', m[...,1:])
print('Elementos mayores de 5:\n', m[m > 5])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Fila 1 en adelante:
 [[4 5 6]
 [7 8 9]]
Columna 1 en adelante:
 [[2 3]
 [5 6]
 [8 9]]
Elementos mayores de 5:
 [6 7 8 9]


__¡Cuidado!__ Arrays no multiplicables por sus dimensiones, producen operaciones permitidas por broadcasting:

In [ ]:
n = np.arange(1,5)
m = np.arange(10,50,10)
print(n)
print(m)
print(n.shape, m.shape)
print(n * m)
print(n + m)

[1 2 3 4]
[10 20 30 40]
(4,) (4,)
[ 10  40  90 160]
[11 22 33 44]


In [ ]:
o = np.random.rand(4,4)
print(o)
print(o.shape)
p = n * o
print(p)
print(p.shape)

[[0.3661347  0.53206107 0.13109586 0.63908972]
 [0.4845614  0.90456297 0.28881199 0.0223751 ]
 [0.69771134 0.69657288 0.92107551 0.28229151]
 [0.46989795 0.90050646 0.69231849 0.67210632]]
(4, 4)
[[0.3661347  1.06412214 0.39328759 2.55635886]
 [0.4845614  1.80912594 0.86643597 0.08950041]
 [0.69771134 1.39314577 2.76322652 1.12916604]
 [0.46989795 1.80101291 2.07695546 2.68842528]]
(4, 4)


In [ ]:
print(n)
print(o)
print(n + o)

[1 2 3 4]
[[0.3661347  0.53206107 0.13109586 0.63908972]
 [0.4845614  0.90456297 0.28881199 0.0223751 ]
 [0.69771134 0.69657288 0.92107551 0.28229151]
 [0.46989795 0.90050646 0.69231849 0.67210632]]
[[1.3661347  2.53206107 3.13109586 4.63908972]
 [1.4845614  2.90456297 3.28881199 4.0223751 ]
 [1.69771134 2.69657288 3.92107551 4.28229151]
 [1.46989795 2.90050646 3.69231849 4.67210632]]


In [ ]:
q = np.arange(0,60,5).reshape(3,4)
print(q)
for x in np.nditer(q):
    print(x)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0
5
10
15
20
25
30
35
40
45
50
55


In [ ]:
print(q)
print(q.flatten())
print(q.transpose())
print(q.T)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[ 0  5 10 15 20 25 30 35 40 45 50 55]
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


In [ ]:
r = np.array([[1,2],[3,4]])
s = np.array([[5,6],[7,8]])
print(r)
print(s)
print('Concatenar:')
print(np.concatenate((r,s)))
print(np.concatenate((r,s),axis = 1))
print('Stacking:')
print(np.stack((r,s)))
print(np.stack((r,s)).shape)
print(np.stack((r,s),0))
print(np.stack((r,s),1))
print(np.stack((r,s),2))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Concatenar:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
Stacking:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [ ]:
t = np.arange(9)
print(t)
print(np.split(t,3))
print(np.split(t,[4,7]))
t = t.reshape(3,3)
print(t)
print(np.insert(t,2,[11,12]))
print(np.insert(t,2,[11,12,13],axis = 0))
print(np.insert(t,2,[11,12,13],axis = 1))
print(np.delete(t,2))
print(np.delete(t,2,axis = 0))
print(np.delete(t,np.s_[::2]))

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 0  1 11 12  2  3  4  5  6  7  8]
[[ 0  1  2]
 [ 3  4  5]
 [11 12 13]
 [ 6  7  8]]
[[ 0  1 11  2]
 [ 3  4 12  5]
 [ 6  7 13  8]]
[0 1 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]]
[1 3 5 7]


Funciones estadísticas:

In [ ]:
print(s)
print(s.max())
print(s.min())
print(s.ptp())    # Rango: max - min
print(s.mean())
print(np.mean(s))
print(np.median(s))
print(s.std())
print(s.var())

[[5 6]
 [7 8]]
8
5
3
6.5
6.5
6.5
1.118033988749895
1.25


Álgebra lineal, operaciones matriciales:

In [6]:
import numpy.matlib

print(np.matlib.empty((2,2)))
print(type(np.matlib.empty((2,2))))
print(np.matlib.zeros((2,2)))
print(np.matlib.ones((2,2)))
print(np.matlib.eye(4,4,-1))
print(np.matlib.identity(3))
print(np.matlib.rand(3,3))

[[1. 1.]
 [1. 0.]]
<class 'numpy.matrix'>
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.63253325 0.06517959 0.0520073 ]
 [0.45220769 0.4918127  0.60596538]
 [0.44093298 0.44077131 0.09428542]]


In [7]:
u = np.matrix([[1,0],[0,1]])
v = np.matrix([[4,1],[2,2]])
w = np.matrix([1,2])
print(u.shape)
print(v.shape)
print(w.shape)
print(np.matmul(u,v))
print(np.matmul(w,u))
try:
    print(np.matmul(u,w))
except ValueError as e:
    print(e)

(2, 2)
(2, 2)
(1, 2)
[[4 1]
 [2 2]]
[[1 2]]
matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)


In [8]:
print(v)
print(np.linalg.inv(v))
print(np.matmul(v, np.linalg.inv(v)))

[[4 1]
 [2 2]]
[[ 0.33333333 -0.16666667]
 [-0.33333333  0.66666667]]
[[1. 0.]
 [0. 1.]]


## Matplotlib

Tenemos disponibles los modos interactivo en el notebook y en línea.

In [10]:
from matplotlib import pyplot as plt
%matplotlib notebook
#%matplotlib inline

x = np.arange(1,11)
y = 2 * x + 5
plt.title('Matplotlib')
plt.xlabel('x')
plt.ylabel('y')
plt.plot(x,y)
plt.show()

<IPython.core.display.Javascript object>

In [11]:
plt.figure()    # Inicializa una nueva gráfica, necesario para ""%matplotlib notebook"

plt.title('Matplotlib')
plt.xlabel('x')
plt.ylabel('y')
plt.plot(x,y)
plt.show()

<IPython.core.display.Javascript object>

In [12]:
plt.figure()

plt.title('Matplotlib')
plt.xlabel('y')
plt.ylabel('x')
plt.plot(y,x, '--y')
plt.show()

<IPython.core.display.Javascript object>

In [13]:
x = [5,8,10]
y = [12,16,6]
x2 = [6,9,11]
y2 = [6,15,7]

plt.figure()

plt.bar(x,y,align='center')
plt.bar(x2,y2,color='g',align='center')
plt.title('Gráfica barras')
plt.ylabel('Y axis')
plt.xlabel('X axis')
plt.show()

<IPython.core.display.Javascript object>

In [14]:
t = np.array([22,87,5,43,56,73,55,54,11,20,51,5,79,31,27])

hist,bins = np.histogram(t,bins=[0,20,40,60,80,100])
print(hist, bins)

plt.figure()

plt.hist(t, bins)
plt.title('Histograma')
plt.show()

[3 4 5 2 1] [  0  20  40  60  80 100]


<IPython.core.display.Javascript object>

In [15]:
p = np.arange(0.,5.,0.2)

plt.figure()

plt.plot(p,p,'r--',p,p**2,'bs',p,p**3,'g^',linewidth=2.0)
plt.show()

<IPython.core.display.Javascript object>

In [16]:
def f(t):
    return np.exp(-t)*np.cos(2*np.pi*t)

t1 = np.arange(0.,5.,0.1)
t2 = np.arange(0.,5.,0.02)

plt.figure(7)
plt.subplot(211)
plt.plot(t1,f(t1),'bo',t2,f(t2),'k')

plt.subplot(212)
plt.plot(t2,np.cos(2*np.pi*t2),'r--')
plt.show()

<IPython.core.display.Javascript object>

In [17]:
plt.figure(8)
plt.subplot(211)
plt.plot([1,2,3])

plt.figure(9)
plt.plot([4,5,6])

plt.figure(8)
plt.subplot(212)
plt.plot([4,5,6])

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [18]:
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter

fig = plt.figure()
ax = fig.gca(projection='3d')

x = np.arange(-5,5,0.25)
y = np.arange(-5,5,0.25)
x, y = np.meshgrid(x,y)
z = np.sin(np.sqrt(x**2+y**2))

surf = ax.plot_surface(x,y,z,cmap=cm.coolwarm,linewidth=0,
                       antialiased=False)

ax.set_zlim(-1.01,1.01)
ax.zaxis.set_major_locator(LinearLocator(10))
ax.zaxis.set_major_formatter(FormatStrFormatter('%.02f'))

fig.colorbar(surf,shrink=0.5,aspect=5)

plt.show()

<IPython.core.display.Javascript object>

## Scikit-learn

In [19]:
from sklearn import datasets

iris = datasets.load_iris()
digits = datasets.load_digits()

print(digits.data)
print(digits.target)
print(digits.images[0])

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[0 1 2 ... 8 9 8]
[[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]


In [20]:
from sklearn import svm

clf = svm.SVC(gamma=0.001,C=100.)

clf.fit(digits.data[:-1],digits.target[:-1])

plt.figure(figsize=(3,3))
plt.imshow(digits.images[-1],cmap=plt.cm.gray_r,interpolation='nearest')
plt.show()

print(clf.predict(digits.data[-1:]))

<IPython.core.display.Javascript object>

[8]


In [21]:
import pickle

s = pickle.dumps(clf)

clf2 = pickle.loads(s)

print(clf2.predict(digits.data[-1:]))

[8]


## Ejercicios

### Crea un array de 3 dimensiones y tamaño 2x3x4 con elementos aleatorios e imprímelo en pantalla

In [34]:
u = np.matlib.rand(4,6)
print( np.array(u).reshape(2,3,4))
print(u)


[[[0.09222611 0.88252367 0.76884681 0.62486575]
  [0.4415658  0.67414014 0.42462593 0.77449136]
  [0.48234872 0.45919727 0.71079317 0.6717563 ]]

 [[0.23666657 0.58243905 0.52948793 0.9294154 ]
  [0.25810762 0.03719195 0.14331784 0.15545521]
  [0.0574958  0.96152898 0.56179751 0.74259087]]]
[[0.09222611 0.88252367 0.76884681 0.62486575 0.4415658  0.67414014]
 [0.42462593 0.77449136 0.48234872 0.45919727 0.71079317 0.6717563 ]
 [0.23666657 0.58243905 0.52948793 0.9294154  0.25810762 0.03719195]
 [0.14331784 0.15545521 0.0574958  0.96152898 0.56179751 0.74259087]]


### Crea un nuevo array de 2 dimensiones, de elementos aleatorios y tamaño 100x14, e insértale una columna de 1s a la izquierda

### Crea un nuevo array de 2 dimensiones, de elementos aleatorios y tamaño 1x15 y multiplica su transpuesta por el resultado del ejercicio anterior

### Representa en una gráfica el resultado del ejercicio anterior